### ISSUE TITLE
adjust distance with slider

### ISSUE THREAD

**Issue by meganrm** [meganrm/indivisible-map#26]

**Comment by meganrm** [comment]
using this slider: https://ant.design/components/slider/

**Comment by pdvorchik** [comment]
@meganrm Is this for the group search, event search, or both?  Do we want to remove the map zoom controls and use this instead?  Any preference on location (map overlay vis a vis sidebar)?

**Comment by meganrm** [comment]
For both. And all this should do it change the value in the state. So don’t change the map controls. This is for part of the search, so I would put it right under the search bar.
