### ISSUE TITLE
displaying groups

### ISSUE THREAD

**Issue by meganrm** [meganrm/indivisible-map#31]
1. Name (with name linked to website if they have, and if not, then facebook if they have, and if not, then twitter if they have, and if not, mailto: email if they have)
2. Website if they have
3. Facebook if they have
4. Twitter if they have
5. Email if they have (this is called Public Group Email - we don't want any other emails linked)

**Comment by pdvorchik** [comment]
@meganrm I'm not seeing these fields in `group-dummy-data.json`, is there some other place I should be looking?

If they're not in there yet, what naming conventions do you want to use for the various fields?
